version: "{build}"
clone_depth: 1
image: Visual Studio 2019

build_script:
- call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat" x86_amd64
- ggbuild\lua.exe make.lua release > build.ninja
- ggbuild\ninja.exe -v -k 0
- ggbuild\lua.exe ggbuild\ninja_timeline.lua
- ggbuild\ducible.exe release\mudgangster.exe
- makensis.exe installer\mudgangster.nsi

artifacts:
- path: installer/MudGangsterInstaller.exe

deploy:
- provider: GitHub
  auth_token:
    secure: uTKqq6j9jmjRhhb8XGIpL1Xp2Fc1QtPeq0aaWbqXa5Tz6lL/dTVfrfFpceQDnbz1
  artifact: installer/MudGangsterInstaller.exe
